<a href="https://colab.research.google.com/github/YosrMemmi/Project-2/blob/main/Project_2_Part_1_(Core).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

##First choice: dataset 1

In [5]:
import pandas as pd
# Load data
path = '/content/drive/MyDrive/Coding Dojo/StudentFolders16wk24wk/CodingDojo/02-IntroML/Week07/Data/Metabolic  Syndrome.csv'
df = pd.read_csv(path)
df.head()

,seqn,Age,Sex,Marital,Income,Race,WaistCirc,BMI,Albuminuria,UrAlbCr,UricAcid,BloodGlucose,HDL,Triglycerides,MetabolicSyndrome
0,62161,22,Male,Single,8200.0,White,81.0,23.3,0,3.88,4.9,92,41,84,No MetSyn
1,62164,44,Female,Married,4500.0,White,80.1,23.2,0,8.55,4.5,82,28,56,No MetSyn
2,62169,21,Male,Single,800.0,Asian,69.6,20.1,0,5.07,5.4,107,43,78,No MetSyn
3,62172,43,Female,Single,2000.0,Black,120.4,33.3,0,5.22,5.0,104,73,141,No MetSyn
4,62177,51,Male,Married,NaN,Asian,81.1,20.1,0,8.13,5.0,95,43,126,No MetSyn

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2401 entries, 0 to 2400
Data columns (total 15 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   seqn               2401 non-null   int64
 1   Age                2401 non-null   int64
 2   Sex                2401 non-null   object
 3   Marital            2193 non-null   object
 4   Income             2284 non-null   float64
 5   Race               2401 non-null   object
 6   WaistCirc          2316 non-null   float64
 7   BMI                2375 non-null   float64
 8   Albuminuria        2401 non-null   int64
 9   UrAlbCr            2401 non-null   float64
 10  UricAcid           2401 non-null   float64
 11  BloodGlucose       2401 non-null   int64
 12  HDL                2401 non-null   int64
 13  Triglycerides      2401 non-null   int64
 14  MetabolicSyndrome  2401 non-null   object
dtypes: float64(5), int64(6), object(4)
memory usage: 281.5+ KB

1. Source of data
   
   The pre-approved Datasets:

2. Brief description of data

   This dataset presents different informations about patients to know if they have a metabolic syndrom

3. What is the target?
   
   'MetabolicSyndrome'


4. What does one row represent? (A person? A business? An event? A product?)

   A patient

5. Is this a classification or regression problem?

   It's a classification problem

6. How many features does the data have?

   14 features

7. How many rows are in the dataset?

   2401 rows

##Second choice: dataset 2

In [8]:
# Load data
path2 = '/content/drive/MyDrive/Coding Dojo/StudentFolders16wk24wk/CodingDojo/02-IntroML/Week07/Data/archive (1).zip (Unzipped Files)/pokemon_alopez247.csv'
df2 = pd.read_csv(path2)
df2.head()

,Number,Name,Type_1,Type_2,Total,HP,Attack,Defense,Sp_Atk,Sp_Def,...,Color,hasGender,Pr_Male,Egg_Group_1,Egg_Group_2,hasMegaEvolution,Height_m,Weight_kg,Catch_Rate,Body_Style
0,1,Bulbasaur,Grass,Poison,318,45,49,49,65,65,...,Green,True,0.875,Monster,Grass,False,0.71,6.9,45,quadruped
1,2,Ivysaur,Grass,Poison,405,60,62,63,80,80,...,Green,True,0.875,Monster,Grass,False,0.99,13.0,45,quadruped
2,3,Venusaur,Grass,Poison,525,80,82,83,100,100,...,Green,True,0.875,Monster,Grass,True,2.01,100.0,45,quadruped
3,4,Charmander,Fire,NaN,309,39,52,43,60,50,...,Red,True,0.875,Monster,Dragon,False,0.61,8.5,45,bipedal_tailed
4,5,Charmeleon,Fire,NaN,405,58,64,58,80,65,...,Red,True,0.875,Monster,Dragon,False,1.09,19.0,45,bipedal_tailed

In [9]:
df2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 721 entries, 0 to 720
Data columns (total 23 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Number            721 non-null    int64
 1   Name              721 non-null    object
 2   Type_1            721 non-null    object
 3   Type_2            350 non-null    object
 4   Total             721 non-null    int64
 5   HP                721 non-null    int64
 6   Attack            721 non-null    int64
 7   Defense           721 non-null    int64
 8   Sp_Atk            721 non-null    int64
 9   Sp_Def            721 non-null    int64
 10  Speed             721 non-null    int64
 11  Generation        721 non-null    int64
 12  isLegendary       721 non-null    bool
 13  Color             721 non-null    object
 14  hasGender         721 non-null    bool
 15  Pr_Male           644 non-null    float64
 16  Egg_Group_1       721 non-null    object
 17  Egg_Group_2       191 non-null    object
 18  hasMegaEvolution  721 non-null    bool
 19  Height_m          721 non-null    float64
 20  Weight_kg         721 non-null    float64
 21  Catch_Rate        721 non-null    int64
 22  Body_Style        721 non-null    object
dtypes: bool(3), float64(3), int64(10), object(7)
memory usage: 114.9+ KB

1. Source of data
   
   Kaggle

2. Brief description of data

   This dataset presents different informations about pokemons

3. What is the target?
   
   'Catch_Rate'


4. What does one row represent? (A person? A business? An event? A product?)

   A pokemon

5. Is this a classification or regression problem?

   It's a regression problem

6. How many features does the data have?

   22 features

7. How many rows are in the dataset?

   721 rows